"""minor updates

Revision ID: 29152ea28d4d
Revises: 69ad9de41a59
Create Date: 2016-04-27 02:54:42.490897

"""

# revision identifiers, used by Alembic.
revision = '29152ea28d4d'
down_revision = '69ad9de41a59'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('observations', 'time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('observations', 'timestamp')
    ### end Alembic commands ###
